#release configuration
#Thu Apr 09 13:47:22 CEST 2026
projectVersionPolicyId=default
project.dev.fr.ign.validator\:validator-plugin-pcrs=4.5.0-SNAPSHOT
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
project.rel.fr.ign.validator\:validator-plugin-cnig=4.4.20
pinExternals=false
project.scm.fr.ign.validator\:validator.tag=v4.4.9
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
project.dev.fr.ign.validator\:validator-cli=4.5.0-SNAPSHOT
pushChanges=true
project.dev.fr.ign.validator\:validator-core=4.5.0-SNAPSHOT
project.rel.fr.ign.validator\:validator-plugin-dgpr=4.4.20
project.rel.fr.ign.validator\:validator-plugin-pcrs=4.4.20
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
project.rel.fr.ign.validator\:validator=4.4.20
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
project.scm.fr.ign.validator\:validator.url=https\://github.com/IGNF/validator
completedPhase=end-release
project.rel.fr.ign.validator\:validator-core=4.4.20
scm.url=scm\:git\:git@github.com\:IGNF/validator.git
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.tagNameFormat=v@{project.version}
project.rel.fr.ign.validator\:validator-cli=4.4.20
project.dev.fr.ign.validator\:validator=4.5.0-SNAPSHOT
project.dev.fr.ign.validator\:validator-plugin-dgpr=4.5.0-SNAPSHOT
scm.tag=v4.4.20
project.scm.fr.ign.validator\:validator.developerConnection=scm\:git\:git@github.com\:IGNF/validator.git
project.dev.fr.ign.validator\:validator-plugin-cnig=4.5.0-SNAPSHOT
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
